### ISSUE TITLE
DEBUG_BACKTRACE_IGNORE_ARGS constant missing in PHP < 5.3.6

### ISSUE THREAD

**Issue by enachesilviu** [digitalnature/php-ref#29]
Hello,

There's an error on line 2667 in this file: https://github.com/digitalnature/php-ref/blob/master/ref.php

I'm having difficulties using the well known CentOS 6.x series with php provided by default repository, version 5.3.3. Your code throws a warning due to the fact that I'm missing DEBUG_BACKTRACE_IGNORE_ARGS constant that was added in php 5.3.6. Replacing the package with something else or compiling a newer version of php is not an acceptable fix within the institution policy.

Would you consider implementing a fix for this ? If it helps: as far as I searched the web and tested locally on my machine (php 5.6.9) I evaluated this constant to be an integer of value 2. Also, I used composer to install the library.

**Comment by digitalnature** [comment]
fixed. thanks
