### ISSUE TITLE
preg_grep() error line 773

### ISSUE THREAD

**Issue by idiotstrike** [digitalnature/php-ref#32]
ErrorException in ref.php line 773:
preg_grep(): Compilation failed: unknown property name after \P or \p at offset 12

**Comment by Bukashk0zzz** [comment]
Have same issue
ErrorException in ref.php line 804:
preg_grep(): Compilation failed: unknown property name after \P or \p at offset 12

**Comment by Bukashk0zzz** [comment]
I changed now all ok.

```php
if(!$function || !preg_grep("/{$function}/i" , static::$config['shortcutFunc']))
```

to 

```php
if(!$function || !in_array((string)$function , static::$config['shortcutFunc']))
```

**Comment by DeeJaVu** [comment]
its line 786
