### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Lukasss93** [digitalnature/php-ref#49]
Hi, 
I found this error using `r()` method with any class with PHP 7.2
> count(): Parameter must be an array or an object that implements Countable

**Comment by digitalnature** [comment]
Need some sample code to reproduce the error

**Comment by alystair** [comment]
I got the same error when I made a wrapper around r() for an array of vars to be extra lazy, clearly it's the wrong way about things ;)

```php
function dd(array $vars = [],bool $die = false){
    foreach ($vars as $var) {
        r($var);
    }
    if ($die) die();
}
```

**Comment by digitalnature** [comment]
Does it happen with any array? Like `dd([1, 2, 3])` ?

**Comment by alystair** [comment]
You get the countable error on all but the last element in the array. Line 24 of ref.php if `r()` or line 69 for `rt()`

**Comment by digitalnature** [comment]
Ah, this has been fixed in https://github.com/digitalnature/php-ref/commit/da0d2c0d55798470348a2f44adb9144ee2259691

You must be using the "v1.2" release, but I forgot to create a release that includes the last commits...   I`ll just make one now
