### ISSUE TITLE
r($object), throw a ReflectionException

### ISSUE THREAD

**Issue by imnicy** [digitalnature/php-ref#55]
Type: ReflectionException
Code: 0
Message: Internal error: Failed to retrieve the default value
File: E:\Codes\myCodes\imnicy.com\vendor\digitalnature\php-ref\ref.php
Line: 1956

#0 E:\Codes\myCodes\imnicy.com\vendor\digitalnature\php-ref\ref.php(1956): ReflectionParameter->isDefaultValueConstant()
#1 E:\Codes\myCodes\imnicy.com\vendor\digitalnature\php-ref\ref.php(314): ref->evaluate(Object(Nicy\Support\Collection))
#2 E:\Codes\myCodes\imnicy.com\vendor\digitalnature\php-ref\ref.php(40): ref->query(Object(Nicy\Support\Collection), '$result')
#3 E:\Codes\myCodes\imnicy.com\app\Http\Controllers\HomeController.php(16): r(Object(Nicy\Support\Collection))
#4 E:\Codes\myCodes\imnicy.com\framework\src\Handlers\Strategies\RequestResponse.php(43): App\Http\Controllers\HomeController->index(Object(Symfony\Component\HttpFoundation\Request))
......

**Comment by digitalnature** [comment]
Should be handled in https://github.com/digitalnature/php-ref/commit/85512e090ae616e5b564d4ffdc9e11450cc8da46
